security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User\User
                property: email

    firewalls:
        main:
            access_token:
                token_handler: App\Security\AccessTokenHandler
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: /logout

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/user/registration/, roles: PUBLIC_ACCESS }
        - { path: ^/api/user/authenticate/, roles: PUBLIC_ACCESS }
        - { path: ^/api/user/refresh/, roles: PUBLIC_ACCESS }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
