version: '3.8'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: _conf/php-fpm
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./../kraiber-backend/:/var/www/KBackend

  nginx:
    container_name: nginx
    build:
      context: _conf/nginx
    volumes:
      - ./../kraiber-backend/:/var/www/KBackend
      - ./_conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./_conf/nginx/sites/:/etc/nginx/sites-available
      - ./_conf/nginx/conf.d/:/etc/nginx/conf.d
      - ./_conf/logs:/var/log/nginx
    depends_on:
      - php-fpm
    ports:
      - "80:80"
