version: '3.8'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: _conf/php-fpm
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./../kraiber-backend/:/var/www/KBackend

  nginx:
    container_name: nginx
    build:
      context: _conf/nginx
    volumes:
      - ./../kraiber-backend/:/var/www/KBackend
      - ./_conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./_conf/nginx/sites/:/etc/nginx/sites-available
      - ./_conf/nginx/conf.d/:/etc/nginx/conf.d
      - ./_conf/logs:/var/log/nginx
      - ./_conf/nginx/sert:/etc/nginx/ssl
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
